services:
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    container_name: backend_app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - talent_network
    depends_on:
      - mariadb
      # - redis
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    container_name: frontend_app
    ports:
      - "${FRONT_PORT:-5173}:5173"
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    # command: npm install && npm run dev
    depends_on:
      - backend
    networks:
      - talent_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "${NGINX_PORT:-88}:80"
      - "${NGINX_PORT_SEG:-443}:443"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - talent_network

  mariadb:
    image: "mariadb:10.7"
    container_name: database_app
    ports:
      - "${DB_PORT:-3366}:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
      MARIADB_ROOT_HOST: "%"
      MARIADB_DATABASE: "${DB_DATABASE}"
      MARIADB_USER: "${DB_USERNAME}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
      MARIADB_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "mariadb-data:/var/lib/mysql"
      - "./backend/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
    networks:
      - talent_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  talent_network:
    driver: bridge
volumes:
  mariadb-data:
    driver: local
    name: mariadb-data