services:
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    container_name: backend_app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - talent_network
    depends_on:
      - mariadb

  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    container_name: frontend_app
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    networks:
      - talent_network
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_PORT_SEG:-443}:443"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/certs:/etc/certs
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/html:/var/www/certbot
      # - ./docker/nginx/conf.d/default.${APP_ENV}.conf:/etc/nginx/conf.d/default.conf
      # - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
    networks:
      - talent_network

  certbot:
    image: certbot/certbot
    container_name: certbot_ssl
    volumes:
      - ./docker/nginx/certs_letsencrypt:/etc/letsencrypt
      - ./docker/nginx/html:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM;
             while :; do
               if [ \"$APP_ENV\" = \"production\" ]; then
                 certbot renew --webroot -w /var/www/certbot &&
                 nginx -s reload;
               fi;
               sleep 12h & wait $${!};
             done"

  mariadb:
    image: "mariadb:10.7"
    container_name: database_app
    ports:
      - "${DB_PORT:-3366}:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
      MARIADB_ROOT_HOST: "%"
      MARIADB_DATABASE: "${DB_DATABASE}"
      MARIADB_USER: "${DB_USERNAME}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
      MARIADB_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "mariadb-data:/var/lib/mysql"
      - "./backend/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
    networks:
      - talent_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  talent_network:
    driver: bridge

volumes:
  mariadb-data:
    driver: local
    name: mariadb-data
